"""Numerical parity tests against the original R ScReNI reference.

Fixture inputs and R outputs live under ``tests/fixtures/precision_recall/``
and are regenerated by ``generate.R`` (see that file's header for usage).
The tests assert that the Python implementations produce the same numbers
the R code did, within float64 round-off.

The shared ``conftest.py`` installs a stub for ``calculate_precision_recall``
when issue #8 has not yet merged.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from screni.data.calculate_scnetwork_precision_recall import (
    calculate_scnetwork_precision_recall,
)
from screni.data.calculate_scnetwork_precision_recall_top import (
    calculate_scnetwork_precision_recall_top,
)
from screni.data.summary_se import summary_se

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "precision_recall"


# ---- Fixture loading ----------------------------------------------------


@pytest.fixture(scope="module")
def sc_networks() -> dict:
    flat = pd.read_csv(FIXTURE_DIR / "scNetworks_long.csv")
    out: dict = {}
    for net in flat["net"].unique():
        out[net] = {}
        for cell in flat[flat["net"] == net]["cell"].unique():
            sub = flat[(flat["net"] == net) & (flat["cell"] == cell)]
            M = sub.pivot(index="from", columns="to", values="weight")
            idx = sorted(M.index)
            out[net][cell] = M.loc[idx, idx]
    return out


@pytest.fixture(scope="module")
def tf_target_pair() -> list[str]:
    return (FIXTURE_DIR / "TF_target_pair.txt").read_text().splitlines()


@pytest.fixture(scope="module")
def py_pr(sc_networks, tf_target_pair) -> dict:
    return calculate_scnetwork_precision_recall(
        sc_networks, tf_target_pair, top_number=[5, 10]
    )


# ---- Tests --------------------------------------------------------------


@pytest.mark.parametrize("k", [0, 5, 10])
def test_precision_recall_matches_r(py_pr, k):
    """Per-cell precision/recall agrees with R for every cutoff bucket."""
    r_df = pd.read_csv(FIXTURE_DIR / f"r_pr_{k}.csv")
    # R appends ".1", ".2" suffixes on duplicate rownames during rbind.
    r_df["cell"] = r_df["cell"].str.replace(r"\.\d+$", "", regex=True)

    py_df = py_pr[k].reset_index(drop=False).rename(columns={"index": "cell"})
    py_df["scNetwork_type"] = py_df["scNetwork_type"].astype(str)

    merged = r_df.merge(py_df, on=["scNetwork_type", "cell"], suffixes=("_r", "_py"))
    assert len(merged) == len(r_df), (
        f"row mismatch at k={k}: r={len(r_df)} merged={len(merged)}"
    )
    np.testing.assert_allclose(
        merged["precision_r"].to_numpy(),
        merged["precision_py"].to_numpy(),
        atol=1e-12,
    )
    np.testing.assert_allclose(
        merged["recall_r"].to_numpy(),
        merged["recall_py"].to_numpy(),
        atol=1e-12,
    )


@pytest.mark.parametrize(
    "measure, csv_name",
    [("precision", "r_precision_top.csv"), ("recall", "r_recall_top.csv")],
)
def test_precision_recall_top_matches_r(py_pr, measure, csv_name):
    """summary_se output via the top-level function agrees with R."""
    prec_top, rec_top = calculate_scnetwork_precision_recall_top(py_pr, top_number=[5, 10])
    py_df = (prec_top if measure == "precision" else rec_top).copy()
    py_df["scNetwork_type"] = py_df["scNetwork_type"].astype(str)
    py_df["top_number"] = py_df["top_number"].astype(int)

    r_df = pd.read_csv(FIXTURE_DIR / csv_name)
    r_df["scNetwork_type"] = r_df["scNetwork_type"].astype(str)
    r_df["top_number"] = r_df["top_number"].astype(int)

    merged = r_df.merge(
        py_df, on=["scNetwork_type", "top_number"], suffixes=("_r", "_py")
    )
    assert len(merged) == len(r_df)

    for col in ["N", measure, "sd", "se", "ci"]:
        np.testing.assert_allclose(
            merged[f"{col}_r"].astype(float).to_numpy(),
            merged[f"{col}_py"].astype(float).to_numpy(),
            atol=1e-10,
            equal_nan=True,
            err_msg=f"{measure}/{col} disagrees with R",
        )


def test_summary_se_matches_r():
    """``summary_se`` output agrees with R's ``summarySE``."""
    se_in = pd.read_csv(FIXTURE_DIR / "se_input.csv")
    py_se = summary_se(se_in, measurevar="x", groupvars=["g"])
    r_se = pd.read_csv(FIXTURE_DIR / "r_se.csv")

    py_se = py_se.assign(g=py_se["g"].astype(str))
    merged = r_se.merge(py_se, on="g", suffixes=("_r", "_py"))
    assert len(merged) == len(r_se)

    for col in ["N", "x", "sd", "se", "ci"]:
        np.testing.assert_allclose(
            merged[f"{col}_r"].to_numpy(),
            merged[f"{col}_py"].to_numpy(),
            atol=1e-10,
            err_msg=f"summary_se/{col} disagrees with R",
        )
